### ISSUE TITLE
[Seoul, Jamsil] Front-end Developer - Buzzvil

### ISSUE THREAD

**Issue by d4rekanguok** [hivearena/startup-jobs-in-South-Korea#3]
### Developer - Front-end
`Javascript` `AngularJS` `HTML` `CSS` `Django REST framework`

버즈빌에서는 광고 플랫폼에 필요한 front-end를 AngularJS를 활용하여 구축하였습니다. 또한 허니스크린 앱과 버즈빌에서 제공하는 여러 SDK에서 필요로하는 페이지의 많은 부분이 웹 기반으로 되어 있습니다. 사용자의 요구사항을 능동적으로 파악하여 front-end를 구현하고 자동화된 테스트환경을 구축하는 역할을 담당하게 됩니다.

### About the Job
이런 생각을 평소에 가지고 있으셨다면 주저없이 저희 버즈빌에 지원해주세요!

* 사용자 편의를 극대화하는 UI/UX 개발에 관심이 많으신 분
* 자신이 직접 짠 코드로 수백만명의 유저 경험을 변화시키고 싶으신 분
* 다양한 국적을 가진 멤버들로 구성된 글로벌한 팀에서 글로벌하게 일해보고 싶으신 분

### Key Responsibilities
* 버즈빌 광고 플랫폼 front-end 개발
* 웹 어플리케이션 개발
* 웹 개발 테스트 자동화
* Rest API 개발

## Location
On-site, Jamsil, Seoul

## Benefits

* 연금보험: 국민연금(4대보험), 고용보험(4대보험), 산재보험(4대보험), 건강보험(4대보험)
* 급여제도: 우수사원포상, 스톡옵션, 퇴직금
* 수당제도: 연/월차수당
* 동호회/조직: 사내동호회 운영
* 회사분위기: 호칭/서열파괴, 인재육성 중시, 가족같은분위기, 회식강요 안함, 야근강요 안함
* 명절/기념일: 명절선물/귀향비
* 의료/건강: 건강검진
* 출산/육아: 산전 후 휴가, 육아휴직
* 사무실환경: 휴게실, 수면실, 샤워실, 회의실(PT가능), 카페테리아, 무선인터넷, 게임방(플스 등)
* 의복관련: 자유복장
* 식사관련: 아침식사 및 간식 제공, 냉장고있음, 전자레인지 있음, 음료제공(차,커피)
* 교통/출퇴근: 주차장 제공
* 지급품: 맥북, 듀얼모니터
* 지원금/대출: 각종 경조사 지원, 결혼준비 지원, MT비 지원
* 교육/훈련: 신입사원교육(OJT), 도서구입비지원, 사내외국어강좌, 교육비 지원, 자기계발비 지원
* 휴일/휴가: 연차, 경조휴가제, 반차
* 회사 행사: 우수사원시상식, 워크샵, 야유회, 송년회

## Requirements

List of things that company is looking for

### Required:
* 여러 데이터베이스의 성능 특성에 대해 이해하고 적절하게 활용 및 최적화 하실 수 있는 분
* AWS에 인프라 구축에 익숙하신 분
* 자료구조 / 알고리즘 / OS / Network 관련 기초지식을 보유하신 분
* 코딩이 즐거우신 분
* 자신의 코드에 대해 책임질 수 있는 분
* 능동적인 업무 수행과 협업을 중요하게 생각 하시는 분
* 스타트업 문화에 대한 관심 및 빠르게 업무를 진행할 수 있는 역량이 있으신 분

## About a company

버즈빌에서 글로벌 모바일 플랫폼 서비스를 함께 개발할 역량있는 안드로이드 개발자를 찾습니다.

저희는 모바일에서 가장 효과적인 광고 플랫폼이 되기위해 모바일 첫화면을 끊임없이 고민하는 회사로서,
* 한국/일본/대만의 B2C 잠금화면 서비스인 "허니스크린"
* SDK로 다양한 어플리케이션에 잠금화면을 탑재할 수 있는 "버즈스크린"
* 그리고 다양한 제휴사와 연동되어있는 모바일 광고 네트워크인 "버즈애드"
를 운영하고 있습니다.

이에 대한 성과를 인정받아 2014년에 소프트뱅크 벤처스로부터 30억을 투자 받았고, 2015년에는 소프트뱅크 벤처스로부터 베스트 포트폴리오로 선정되는 영광을 얻었습니다. 그리고 2015년 12월에는 유수 VC들로부터 130억원의 Series B 투자 유치에 성공하였습니다.

버즈빌에 어떤 사람들이 일하는지, 그리고 어떤 문화를 갖고 있는지 더 자세히 알고 싶으시면 "블로그"에 방문 해주세요.

## Company information
[buzzvil.com/career](https://www.buzzvil.com/career/)

## How to apply

[Please apply through Workable](https://www.workable.com/j/8A8481A1AC)

**Comment by hivearena** [comment]
Add a label
