### ISSUE TITLE
[Seoul, Jamsil] Product Manager - Buzzvil

### ISSUE THREAD

**Issue by d4rekanguok** [hivearena/startup-jobs-in-South-Korea#4]
### Product Manager

버즈빌에서 운영하고 있는 프로덕트를 발전시키기 위해 필요한 기능은 무엇인지 그리고 어떠한 프로덕트를 만들어야 하는지를 끊임없이 고민하고 고민의 결과가 실제적인 프로덕트로 나올 수 있도록 프로덕트의 처음과 끝을 도맡아 기획 및 관리하는 역할입니다. 

### Responsibilities

* 프로덕트에 필요한 기능들을 정의하고 개발자들이 쉽게 개발할 수 있는 형태로 기획하는 역할을 해야 합니다.
* 다양한 이해관계자(내부 팀, 외부 파트너 및 고객)들의 요구사항을 수렴하고 그 중 프로덕트의 발전에 도움이 되는 의견이 무엇인지 판단하고 실제 개발될 수 있도록 의견을 조정하고 기획하는 역할을 해야 합니다.
* 여러 개발과제 중 어떠한 것이 중요하고 우선순위가 높은 것인지 판단하고, 그 우선순위에 의해 개발이 진행될 수 있도록 업무를 조정하고 개발 일정을 관리하는 역할을 해야 합니다.
* 기획한 내용 또는 개발된 내용들이 배포되기 전 요구사항은 제대로 반영되었는지 혹시 버그는 없는지를 최종적으로 확인하는 역할을 해야 합니다.

## Location
On-site, Jamsil, Seoul

## Benefits

* 연금보험: 국민연금(4대보험), 고용보험(4대보험), 산재보험(4대보험), 건강보험(4대보험)
* 급여제도: 우수사원포상, 스톡옵션, 퇴직금
* 수당제도: 연/월차수당
* 동호회/조직: 사내동호회 운영
* 회사분위기: 호칭/서열파괴, 인재육성 중시, 가족같은분위기, 회식강요 안함, 야근강요 안함
* 명절/기념일: 명절선물/귀향비
* 의료/건강: 건강검진
* 출산/육아: 산전 후 휴가, 육아휴직
* 사무실환경: 휴게실, 수면실, 샤워실, 회의실(PT가능), 카페테리아, 무선인터넷, 게임방(플스 등)
* 의복관련: 자유복장
* 식사관련: 아침식사 및 간식 제공, 냉장고있음, 전자레인지 있음, 음료제공(차,커피)
* 교통/출퇴근: 주차장 제공
* 지급품: 맥북, 듀얼모니터
* 지원금/대출: 각종 경조사 지원, 결혼준비 지원, MT비 지원
* 교육/훈련: 신입사원교육(OJT), 도서구입비지원, 사내외국어강좌, 교육비 지원, 자기계발비 지원
* 휴일/휴가: 연차, 경조휴가제, 반차
* 회사 행사: 우수사원시상식, 워크샵, 야유회, 송년회

## Requirements

List of things that company is looking for

### Required:
* 프로덕트를 마치 자신의 몸처럼 생각하고 끊임없이 고민할 수 있는 Product Ownership이 필수적입니다.
* 다양한 이해관계자들의 요구사항을 듣고 의견을 조정해야 하기에 뛰어난 커뮤니케이션 역량을 필요로 합니다.
* 개발의 처음과 끝을 도맡아 관리해야 하기에 꼼꼼한 업무처리 및 일정관리 역량을 필요로 합니다.
* 필요한 기능이 무엇인지, 어떠한 우선순위에 의해서 진행해야 하는지를 판단해야 하기에 논리적이고 기획적인 사고를 필요로 합니다.
* 현재 얼마나 알고 있고 경력이 있느냐 보다는 얼마나 빠르게 배워 내것으로 만들 수 있는가에 대한 학습 능력이 더욱 중요하다고 생각합니다. 저희는 Fast learner를 필요로 합니다.
* 개발팀과 커뮤니케이션 하고 함께 일해야 하기에 기본적인 개발 지식을 필요로 합니다.

### Desirable:
그리고 필수적인 요소는 아니지만, 아래의 요소를 가지고 있으시다면 더욱 좋습니다.

* 당연히 기획 및 프로덕트 매니저 업무를 이전에 해보신 경험이 있으시다면 좋습니다.
* 모바일 서비스, 모바일(인터넷) 광고 산업에서 일해보신 경험이 있으시다면 좋습니다.
* B2B 프로덕트 또는 플랫폼을 기획해보신 경험이 있으시다면 좋습니다.
* 글로벌 팀과 일을 하실 기회가 많기 때문에 영어를 능숙하게 사용하실 수 있으시면 좋습니다.

## About a company

버즈빌에서 글로벌 모바일 플랫폼 서비스를 함께 개발할 역량있는 안드로이드 개발자를 찾습니다.

저희는 모바일에서 가장 효과적인 광고 플랫폼이 되기위해 모바일 첫화면을 끊임없이 고민하는 회사로서,
* 한국/일본/대만의 B2C 잠금화면 서비스인 "허니스크린"
* SDK로 다양한 어플리케이션에 잠금화면을 탑재할 수 있는 "버즈스크린"
* 그리고 다양한 제휴사와 연동되어있는 모바일 광고 네트워크인 "버즈애드"
를 운영하고 있습니다.

이에 대한 성과를 인정받아 2014년에 소프트뱅크 벤처스로부터 30억을 투자 받았고, 2015년에는 소프트뱅크 벤처스로부터 베스트 포트폴리오로 선정되는 영광을 얻었습니다. 그리고 2015년 12월에는 유수 VC들로부터 130억원의 Series B 투자 유치에 성공하였습니다.

버즈빌에 어떤 사람들이 일하는지, 그리고 어떤 문화를 갖고 있는지 더 자세히 알고 싶으시면 "블로그"에 방문 해주세요.

## Company information
[buzzvil.com/career](https://www.buzzvil.com/career/)

## How to apply

[Please apply through Workable](https://www.workable.com/j/0EA3A800E0)

**Comment by hivearena** [comment]
Add a label
